### ISSUE TITLE
Update workshop to Styled System 5 APIs

### ISSUE THREAD

**Issue by sapegin** [component-driven/component-driven-development#28]
https://styled-system.com/guides/migrating

- [ ] Use [system](https://styled-system.com/api#system) to create custom props for components like Icon. Also https://styled-system.com/guides/migrating#custom-styles
- [x] Update [variant](https://styled-system.com/api#variant) examples
- [x] Add [variants](https://styled-system.com/api#variants)
- [x] Remove `themeGet` since it's discouraged?
- [ ] Make use of shorthand props more explicit during exercises?
- [ ] Add https://styled-system.com/guides/color-modes

**Comment by okonet** [comment]
I think we'd also need to update excerices to cover updated and new topics such as:

- [ ] Use [system](https://styled-system.com/api#system) to create custom props for components like Icon
- [ ] Update [variant](https://styled-system.com/api#variant) examples
- [ ] Add [variants](https://styled-system.com/api#variants)
- [ ] Remove `themeGet` since it's discouraged?
- [ ] Make use of shorthand props more explicit during exercises?

Thoughts?

**Comment by sapegin** [comment]
I have a commit removing `themeGet` but I need do a bit of testing ;-)

> Use system to create custom props for components like Icon

Maybe, but at the very end and optional ;-)

> Update variant examples
> Add variants

Worth exploring, I do use variants on my sites now. But the issues with dynamic/nested theming still exists.

> Make use of shorthand props more explicit during exercises?

What do you mean? Which shorthands? `mt`?

**Comment by okonet** [comment]
I'm editing the comment. Please hold on :)

**Comment by okonet** [comment]
> at the very end and optional

I think this is quite important and should be thought during primitives part since it's often required to use same scales but render different CSS props. 

I can work on an exercise.

**Comment by sapegin** [comment]
Many topics are important but we should be very careful with the order and priorities: which exercises we can skip and which we can't.

**Comment by sapegin** [comment]
This should fix nesting with variants: https://github.com/styled-system/styled-system/pull/583
