### ISSUE TITLE
Margin props on Heading are broken

### ISSUE THREAD

**Issue by sapegin** [component-driven/component-driven-development#32]
Margin props stopped to work on `Heading` component after styled-system 5 upgrade. Related (but closed) ticket: https://github.com/styled-system/styled-system/issues/599

**Comment by okonet** [comment]
Hmm, looks like we have to drop `defaultProps`?

**Comment by sapegin** [comment]
I'm not sure what's the right solution here: default styles also override props and we need a way to reset default margins or h1-h6.

**Comment by okonet** [comment]
True... why did it work in v4?

**Comment by sapegin** [comment]
No idea ;-/ 

Maybe defining defaults for mt/mr/mb/ml separately will solve it at least for the most common case?

**Comment by angeloashmore** [comment]
It worked before because styles were computed in the same order as the styled-system config, not prop order.

The only solution I could think of was creating a HOF that automatically applies default props:

```jsx
import { typography } from 'styled-system'

const withDefaultProps = Comp => props => <Comp {...Comp.defaultProps} {...props} />

const Input = withDefaultProps(styled.input(typography))

Input.defaultProps = {
  px: 0
}
```

This should work because it ensures the default props are applied *before* props.

This is untested but the idea sounds like it could work.

**Comment by sapegin** [comment]
Yeah, this works, no need for such complexity though ;-)

```js
const HeadingBase = styled.h1`
  ${space};
   /* Other styles */
`;

// Apply default props manually, because styled-system will apply them after
// passed props, so default m prop will overwrite passed mb prop for example
const Heading = props => <HeadingBase {...Heading.defaultProps} {...props} />;

Heading.defaultProps = {
  m: 0,
  size: 'xl',
};
```
