### ISSUE TITLE
Card isn't rendered properly in Safari

### ISSUE THREAD

**Issue by okonet** [component-driven/component-driven-development#43]
![CleanShot 2019-11-12 at 21 58 56](https://user-images.githubusercontent.com/11071/68710364-ad111580-0597-11ea-8a90-674498ca7355.png)

**Comment by sapegin** [comment]
I think I've fixed this once, and it wasn't just Safari ;-/

**Comment by okonet** [comment]
Yes, I also have fixed it on another project and will look into it.
