### ISSUE TITLE
License not showing in GitHub

### ISSUE THREAD

**Issue by okonet** [component-driven/component-driven-development#51]
After the license change it's not showing anymore in the UI on GitHub which I really liked. I'm wondering if that's because of `or` syntax in `package.json` or because of absence of `License.md`.

That said, should we go just CC BY-NC 4.0 instead of GPL v3?

**Comment by sapegin** [comment]
Let's try CC! They are more appropriate for content, not software.

**Comment by okonet** [comment]
Done
